# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6c00705d9f52c21a05a0468b53234ebcb59facd6a7884e3e09ebae5dcc7b1b1f6128d6f7c2cbe28fcc38433fb400a77ceb730a96834a538685627a3bbdfe64b

test:
  secret_key_base: 5bed38cb7dee8e20fbf59ad05fd88ddfcad9253142c507fe117f8a9ab80b6e214dee71e13d03c9b7d61958000dc62571a685996b869d2e3cf406431f55b8eb14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
